[package]
name = "bitcoin-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = { version = "0.32.2", features = ["std", "rand-std"] }
bitcoin-internals = "0.3"
hex_lit = "0.1"
hex-literal = "0.4"
hex = "0.4"
bitcoin_hashes = { version = "0.14", default-features = false }
miniscript = "12.0"
